# Generated by Django 5.1.5 on 2025-02-22 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='sens_name',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='sens_specific',
        ),
        migrations.AddField(
            model_name='sensor',
            name='description',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_name',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(max_length=60, null=True, upload_to='')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='measurement.sensor')),
            ],
        ),
        migrations.DeleteModel(
            name='WorkSensor',
        ),
    ]
