# Generated by Django 5.1.5 on 2025-02-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_sensor_measurement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sr',
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_name',
            field=models.CharField(max_length=60),
        ),
    ]
